apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: employee-pipeline
spec:
  params:
    - name: deployment-name
      type: string
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: image
      type: string
    - name: maven-repo
      type: string
    - name: registry-url
      type: string 

  workspaces:
    - name: shared-workspace

  tasks:

    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-build
      runAfter:
        - git-clone
      taskSpec:
        params:
          - name: MAVEN_MIRROR_URL
            type: string
            value: $(params.maven-repo)
        workspaces:
          - name: source
        steps:
          - name: build
            image: registry.domain1.example.com/ubi9/openjdk-17:latest
            workingDir: $(workspaces.source.path)
            script: |
              echo "Using Maven mirror: $(params.MAVEN_MIRROR_URL)"
              mvn -s /workspace/source/settings.xml clean package
      params:
        - name: MAVEN_MIRROR_URL
          value: $(params.maven-repo)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-image
      runAfter:
        - maven-build
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.image)
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      runAfter:
        - build-image
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc new-app --name $(params.deployment-name) --image=$(params.image) || true
            oc rollout status deployment/$(params.deployment-name)
