apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: employee-trigger-template
spec:
  params:
    - name: git-repo-name
    - name: git-repo-url
    - name: git-revision

  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: pipeline-employee-backend-
      spec:
        serviceAccountName: pipeline

        pipelineRef:
          name: employee-pipeline

        params:
          - name: deployment-name
            value: $(tt.params.git-repo-name)

          - name: git-url
            value: $(tt.params.git-repo-url)

          - name: git-revision
            value: $(tt.params.git-revision)

          - name: image
            value: image-registry.openshift-image-registry.svc:5808/$(context.pipelineRun.namespace)/$(tt.params.git-repo-name):latest

          - name: maven-repo
            value: http://nexus.domain1.example.com:8081/repository/maven-public/

          - name: registry-url
            value: registry.domain1.example.com

        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
