apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: catalog-frontend-build
labels:
  key: value
labels: 
  mylabel: myapp
  
parameters:
# 🔹 NEW PARAMETER (must be added at beginning)

- description: Myapp configuration data
  name: MYPARAMETER
  required: true

- name: NAME
  required: true

- name: GIT_REPO
  required: true

- name: GIT_REF
  value: main

- name: GIT_USERNAME
  required: true

- name: GIT_PASSWORD
  required: true

- name: NPM_MIRROR
  required: true

- name: BACKEND_URL
  required: true

objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
    labels:
      app: catalog-ui
      group: catalog
  spec:
    source:
      type: Git
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_REF}
      sourceSecret:
        name: ${NAME}-git-secret
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:18
          namespace: openshift
        env:
        - name: NPM_MIRROR
          value: ${NPM_MIRROR}
        - name: BACKEND_URL
          value: ${BACKEND_URL}
    output:
      to:
        kind: DockerImage
        name: ${REGISTRY_URL}/${NAME}:latest

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}-git-secret
    labels:
      app: catalog-ui
      group: catalog
  type: kubernetes.io/basic-auth
  stringData:
    username: ${GIT_USERNAME}
    password: ${GIT_PASSWORD}
